# Generated by Django 4.2.7 on 2023-12-14 05:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 5, 59, 29, 863288))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Chatroom',
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('text', 'text'), ('file', 'file')], default='text', max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 5, 59, 29, 863686))),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.chatroom')),
            ],
            options={
                'db_table': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(max_length=255, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='static/documents')),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('In-Progress', 'In-Progress'), ('Resolved', 'Resolved'), ('Disposed', 'Disposed')], max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 5, 59, 29, 864117))),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.chats')),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=255)),
                ('people_num', models.IntegerField()),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 5, 59, 29, 864530))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
