# Generated by Django 4.2.7 on 2023-12-15 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 7, 10, 34, 602312)),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 7, 10, 34, 601095)),
        ),
        migrations.AlterField(
            model_name='chats',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 7, 10, 34, 601488)),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 7, 10, 34, 601908)),
        ),
    ]
