# Generated by Django 4.2.7 on 2023-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookings_ext_id_alter_bookings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='ext_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
