# Generated by Django 4.2.7 on 2023-12-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_tickets_chat_tickets_booking_id_tickets_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
