# Generated by Django 4.2.7 on 2023-12-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_booking_id_tickets_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
