# Generated by Django 4.2.7 on 2023-12-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurants_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='ext_id',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
