[connections.snowflake]
account = "QCQQFNP-JX01681"
user = "SOFTPRODIGY"
password = "4ChEU3ktYFh2UH9"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "ALLBALL_QA"
schema = "QA_DATA"
client_session_keep_alive = true