# Generated by Django 5.0.3 on 2024-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='batchprofilepayload',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
