# Generated by Django 5.0.3 on 2024-04-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_batchprofilepayload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprofilepayload',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('completed', 'completed'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
