# Generated by Django 4.2.5 on 2023-11-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='productImage',
        ),
    ]
