# Generated by Django 4.2.5 on 2023-11-09 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
