version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: >
                bash -c "python manage.py makemigrations &&
                            python manage.py migrate &&
                            python manage.py runserver 0.0.0.0:${PORT}"
        volumes:
            - .:/usr/src/app/
        ports:
            - "${PORT}:${PORT}"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - CELERY_BROKER=${BROKER_URL}
            - CELERY_BACKEND=${BROKER_URL}
        depends_on:
            - redis
        restart: always
    celery:
        build: .
        command: celery -A core worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=${ALLOWED_HOSTS}
            - CELERY_BROKER=${BROKER_URL}
            - CELERY_BACKEND=${BROKER_URL}
        depends_on:
            - django
            - redis


    redis:
        image: "redis:alpine"
        
volumes:
    pgdata:

